#!/bin/sh

# Installation directory
base_dir=`realpath "$0"/../../../../`
#echo base_dir=$base_dir

# Output .rrd file
out=$base_dir/extra/stats/rrd/proxy-1min.rrd
#echo "Output filename: $out"

rrdtool create $out 		    \
--step 60 			    \
DS:nReqProc:COUNTER:120:U:U  	    \
DS:nResProc:COUNTER:120:U:U  	    \
DS:nReqNProc:COUNTER:120:U:U  	    \
DS:nResNProc:COUNTER:120:U:U  	    \
DS:nST:GAUGE:120:U:U 	    	    \
DS:nCT:GAUGE:120:U:U 	    	    \
DS:vm_freememory:GAUGE:120:U:U 	    \
DS:vm_maxmemory:GAUGE:120:U:U  	    \
DS:vm_totalmemory:GAUGE:120:U:U	    \
RRA:AVERAGE:0.5:1:1440		    \
RRA:AVERAGE:0.5:30:336              \
RRA:AVERAGE:0.5:120:372             \
RRA:AVERAGE:0.5:1440:365            \
RRA:MAX:0.5:1:1440		    \
RRA:MAX:0.5:30:336                  \
RRA:MAX:0.5:120:372                 \
RRA:MAX:0.5:1440:365            
