#!/bin/sh

# Installation directory
base_dir=`realpath "$0"/../../../../`
#echo base_dir=$base_dir

# Output .rrd file
out=$base_dir/extra/stats/rrd/location-service-5min.rrd
#echo "Output filename: $out"

rrdtool update $out \
-t nBindings:vm_freememory:vm_maxmemory:vm_totalmemory \
N:`$base_dir/bin/cmdclient -rknc rmi://localhost:1099/LocationService get numBindings vm_freememory vm_maxmemory vm_totalmemory`
