#!/bin/sh

# Installation directory
base_dir=`realpath "$0"/../../../../`
#echo base_dir=$base_dir

# Output .rrd file
out=$base_dir/extra/stats/rrd/registrar-1min.rrd
#echo "Output filename: $out"

rrdtool update $out \
-t nIncReqs:nResOK:nReqRej:nReqErrors:nAuthFails:nCancels:nCCancels:nQueries:nUpdates:nNotFound:vm_freememory:vm_maxmemory:vm_totalmemory \
N:`$base_dir/bin/cmdclient -rknc rmi://localhost:1099/Registrar get numIncReqs numResOK numReqRejects numReqIntErrors numAuthFails numCancels numCompleteCancels numQueries numUpdates numNotFound vm_freememory vm_maxmemory vm_totalmemory`
